### PR TITLE
driver: fix yield in fifottl/utubettl

### LINKED ISSUE #208: Check for infinite loop and sleep after 1000 success iterations for fifottl
It seems that queue/fifottl driver have the same problem (at least I don't see the `processed` counter reset):

https://github.com/tarantool/sharded-queue/pull/49

We need to check the code and fix it if necessary.

### PR DESCRIPTION
**Pull request by oleg-jukovec**
After 1000 processed tuples an iteration fiber yields after each processed tuple. The problem was fixed by resetting a counter of processed tuples without yield.

Closes #208

### CODE REVIEW

**Review by 0x501D — APPROVED** [review]

File: queue/abstract/driver/fifottl.lua [hunk 1]
```diff
@@ -144,6 +144,7 @@ local function fifottl_fiber_iteration(self, processed)
     if estimated > 0 or processed > 1000 then
         -- free refcounter
         estimated = estimated > 0 and estimated or 0
+        processed = 0
```
Comment (LeonidVas) [inline queue/abstract/driver/fifottl.lua:147]: Hmm, I'm not sure this is a good place to reset the counter, because the function returns this value. Wouldn't it be better to reset the counter from the outside?

**Review by LeonidVas — CHANGES_REQUESTED** [review]
Hi! thank you for the patch.
About the title of the commit: "bugfix" not is some subsystem, replace it with something like: "driver: fix yield in fifottl/utubettl".

File: queue/abstract/driver/fifottl.lua (hunk 1 above)
Comment (oleg-jukovec) [reply queue/abstract/driver/fifottl.lua:147]: I don't think so:

Now only one function uses the `processed` variable. In fact the return value is just a state save. If we decide to reset the counter in an external function, then we will spread the responsibility for the variable (and yield + reset) between two functions.

But we could extract wait + reset code into a separate method.

**Comment by oleg-jukovec** [comment]
> with something like: "driver: fix yield in fifottl/utubettl".

Updated.

**Review by LeonidVas — APPROVED** [review]
