### PR TITLE
driver: fix duplicate id error with mvvc on

### LINKED ISSUE #207: IDs of task can duplicated when mvсс is on

### PR DESCRIPTION
**Pull request by better0fdead**
Taking the maximum of the index is an implicit transactions, so it is
always done with 'read-confirmed' mvcc isolation level.
It can lead to errors when trying to make parallel 'put' calls with mvcc enabled.
It is hapenning because 'max' for several puts in parallel will be the same since
read confirmed isolation level makes visible all transactions that finished the commit.
To fix it we wrap it with box.begin/commit and set right isolation level.
Current fix does not resolve that bug in situations when we already are in transaction
since it will open nested transactions.

Further work will be in another PR.
Part of #207

### CODE REVIEW

File: queue/abstract/driver/utubettl.lua [hunk 1]
```diff
@@ -215,9 +215,36 @@ function method.normalize_task(self, task)
...
+    -- taking the maximum of the index is an implicit transactions, so it is
+    -- always done with 'read-confirmed' mvcc isolation level.
+    -- It can lead to errors when trying to make parallel 'put' calls with mvcc enabled.
+    -- It is hapenning because 'max' for several puts in parallel will be the same since
+    -- read confirmed isolation level makes visible all transactions that finished the commit.
+    -- To fix it we wrap it with box.begin/commit and set right isolation level.
+    -- See https://github.com/tarantool/queue/issues/207
+    -- See https://www.tarantool.io/ru/doc/latest/concepts/atomic/txn_mode_mvcc/
+    if check_mvcc_state() then
+        box.begin({txn_isolation = 'read-committed'})
```
Comment (olegrok) [inline queue/abstract/driver/utubettl.lua:241]: Is it possible that external transaction will be opened by user? In that case you will open nested transaction. But Tarantool doesn't support it.

File: queue/abstract/driver/fifo.lua [hunk 2]
```diff
@@ -66,9 +66,36 @@ function method.normalize_task(self, task)
...
 
+-- check if mvcc is enabled
+local function check_mvcc_state()
+    local cfg = box.cfg
+    if cfg['memtx_use_mvcc_engine'] == nil  or cfg['memtx_use_mvcc_engine'] == false then
+        return false
+    end
+
+    return true
+end
```
Comment (Totktonada) [inline queue/abstract/driver/fifo.lua:77]: Just `if box.cfg.memtx_use_mvcc_engine then <...> end` is equivalent and simpler.

File: queue/abstract/driver/fifo.lua [hunk 3]
```diff
@@ -66,9 +66,36 @@ function method.normalize_task(self, task)
...
+    -- It can lead to errors when trying to make parallel 'put' calls with mvcc enabled.
+    -- It is hapenning because 'max' for several puts in parallel will be the same since
+    -- read confirmed isolation level makes visible all transactions that finished the commit.
+    -- To fix it we wrap it with box.begin/commit and set right isolation level.
+    -- See https://github.com/tarantool/queue/issues/207
+    -- See https://www.tarantool.io/ru/doc/latest/concepts/atomic/txn_mode_mvcc/
+    if check_mvcc_state() then
+        box.begin({txn_isolation = 'read-committed'})
+        max = self.space.index.task_id:max()
+        box.commit()
```
Comment (Totktonada) [inline queue/abstract/driver/fifo.lua:94]: Can't we lean on some tarantool's facilities to autogenerate an identifier? For example:

* Use `sequence = true` index option and pass `nil` as an ID.
* Use uuid.

Comment (R-omk) [reply queue/abstract/driver/fifo.lua:94]: Maybe just save counter in lua runtime.
Load from max() at init moment.

Comment (better0fdead) [reply queue/abstract/driver/fifo.lua:94]: Yes, that is other options to fix that issue that we take into account. Currently we disscused to stick to the box.begin/commit.

File: queue/abstract/driver/utubettl.lua (hunk 1 above)
Comment (better0fdead) [reply queue/abstract/driver/utubettl.lua:241]: discussed in a private call

Comment (Totktonada) [reply queue/abstract/driver/utubettl.lua:241]: Please, summarize it for ones who were not on your call.

File: queue/abstract/driver/fifo.lua (hunk 3 above)
Comment (better0fdead) [reply queue/abstract/driver/fifo.lua:94]: > Can you, please, reveal the reasons why the other alternatives were declined?
> 
> The given solution has the problem highlighted by @olegrok with nested transactions at least.

Sure. Problem highlighted by @olegrok  doesn't bother us because of 2 points:
1. Usecases when nested transactions will be opened are rare. (+ it will only happen when mvcc is on)
2. We didn't give promises that in that api there will be no box.begin calls. (that change will not be braking)
So we don't see that it is an issue.

Regarding  @R-omk  suggestion, it will need a lot of additional re-writing of 'queue' logic such as switch in  replicasets for example.

Given that @olegrok issue does'nt bother us. Current fix is enough.

File: queue/abstract/driver/fifo.lua (hunk 2 above)
Comment (better0fdead) [reply queue/abstract/driver/fifo.lua]: changed function

File: queue/abstract/driver/utubettl.lua (hunk 1 above)
Comment (LeonidVas) [reply queue/abstract/driver/utubettl.lua:241]: Hi! The talk was discussing how an external transaction can occur and how valid it is, whether there have been use cases and how valid they are.
I have the following thoughts on this: the work is done with the top-level queue API `put()` (not with operations typical for a DB such as insert/select/...), which doesn't have any contracts on the internals, including the absence of transactions inside.

File: queue/abstract/driver/fifo.lua (hunk 3 above)
Comment (LeonidVas) [reply queue/abstract/driver/fifo.lua:99]: > Maybe just save counter in lua runtime. Load from max() at init moment.

Yes, we considered that option, but in this case we need to update that counter, when the master switched (replicaset mode on) and the current fix looks more localized.

Comment (LeonidVas) [reply queue/abstract/driver/fifo.lua:99]: > Can't we lean on some tarantool's facilities to autogenerate an identifier? For example:
> 
> * Use `sequence = true` index option and pass `nil` as an ID.
> * Use uuid.

Switching to `uuid` will require alter several underlying spaces.
About using sequences, I need some time to think about whether that would work and be a better alternative.

**Review by LeonidVas — CHANGES_REQUESTED** [review]

File: queue/abstract/driver/fifo.lua [hunk 4]
```diff
@@ -66,9 +67,40 @@ function method.normalize_task(self, task)
     return task
 end
 
+-- check if mvcc is enabled
+-- returns true if mvcc is enabled
+local function check_mvcc_state()
+    if not check_version({2, 6, 1}) then
```
[the remark this answers is not in the document]
Comment (better0fdead) [reply queue/abstract/driver/fifo.lua]: removed

File: queue/abstract/driver/fifo.lua [hunk 5]
```diff
@@ -66,9 +67,40 @@ function method.normalize_task(self, task)
...
+
+    -- taking the maximum of the index is an implicit transactions, so it is
+    -- always done with 'read-confirmed' mvcc isolation level.
+    -- It can lead to errors when trying to make parallel 'put' calls with mvcc enabled.
+    -- It is hapenning because 'max' for several puts in parallel will be the same since
+    -- read confirmed isolation level makes visible all transactions that finished the commit.
+    -- To fix it we wrap it with box.begin/commit and set right isolation level.
+    -- See https://github.com/tarantool/queue/issues/207
+    -- See https://www.tarantool.io/ru/doc/latest/concepts/atomic/txn_mode_mvcc/
+    if check_mvcc_state() then
```
[the remark this answers is not in the document]
Comment (better0fdead) [reply queue/abstract/driver/fifo.lua]: changed

File: queue/abstract/driver/fifo.lua [hunk 6]
```diff
@@ -66,9 +67,40 @@ function method.normalize_task(self, task)
...
+
+    return false
+end
+
 -- put task in space
 function method.put(self, data, opts)
-    local max = self.space.index.task_id:max()
+    local max
+
+    -- taking the maximum of the index is an implicit transactions, so it is
```
[the remark this answers is not in the document]
Comment (better0fdead) [reply queue/abstract/driver/fifo.lua]: changed

File: t/220-mvcc.t [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+test:is(tube.name, 'test', 'tube.name')
+test:is(tube.type, 'fifo', 'tube.type')
+
+test:test('concurent take', function(test)
+    test:plan(151)
+
+    local channel = fiber.channel(1000)
+    test:ok(channel, 'channel created')
+
+    local res = {}
```
Comment (LeonidVas) [inline t/220-mvcc.t:36]: What is this table for?

File: t/220-mvcc.t [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+        fiber.create(function(i)
+            local taken = tube:take(1)
+            test:ok(taken, 'Task was taken ' .. i)
+            table.insert(res, { taken })
+            channel:put(true)
+        end, i)
+    end
+
+    fiber.sleep(.1)
+    test:ok(tube:put(1), 'task 1 was put')
```
Comment (LeonidVas) [inline t/220-mvcc.t:47]: Why is this out of the loop?

File: t/220-mvcc.t [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+    for i = 1, 50 do
+        fiber.create(function(i)
+            local taken = tube:take(1)
+            test:ok(taken, 'Task was taken ' .. i)
+            table.insert(res, { taken })
+            channel:put(true)
+        end, i)
+    end
+
+    fiber.sleep(.1)
```
Comment (LeonidVas) [inline t/220-mvcc.t:46]: Why is there a need for `sleep()` here?

File: t/220-mvcc.t [hunk 10]
```diff
@@ -0,0 +1,63 @@
...
+    test:ok(tube:put(1), 'task 1 was put')
+
+    for i = 2, 50 do
+        fiber.create(function(i)
+            test:ok(tube:put(i), 'task ' .. i .. ' was put')
+        end, i)
+    end
+    fiber.sleep(.1)
```
Comment (LeonidVas) [inline t/220-mvcc.t:54]: Why is there a need for `sleep()` here?

File: t/220-mvcc.t [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+test:test('concurent take', function(test)
+    test:plan(151)
+
+    local channel = fiber.channel(1000)
+    test:ok(channel, 'channel created')
+
+    local res = {}
+    for i = 1, 50 do
+        fiber.create(function(i)
+            local taken = tube:take(1)
```
Comment (LeonidVas) [inline t/220-mvcc.t:39]: AFAIU `take()` is fixed in the next commit and should still be broken here.

File: t/220-mvcc.t [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+    test:ok(tube:put(1), 'task 1 was put')
+
+    for i = 2, 50 do
+        fiber.create(function(i)
+            test:ok(tube:put(i), 'task ' .. i .. ' was put')
+        end, i)
+    end
+    fiber.sleep(.1)
+    for i = 1, 50 do
+        test:ok(channel:get(1 / i), 'take was done ' .. i)
```
Comment (LeonidVas) [inline t/220-mvcc.t:56]: Do you use `channel()` to avoid `fiber_obj:join()`?

File: t/220-mvcc.t [hunk 13]
```diff
@@ -0,0 +1,63 @@
...
+
+test:ok(rawget(box, 'space'), 'box started')
+test:ok(queue, 'queue is loaded')
+
+local tube = queue.create_tube('test', 'fifo', { engine = engine })
+test:ok(tube, 'test tube created')
+test:is(tube.name, 'test', 'tube.name')
+test:is(tube.type, 'fifo', 'tube.type')
+
+test:test('concurent take', function(test)
```
Comment (LeonidVas) [inline t/220-mvcc.t:30]: Add a comment describing what the test checks.

**Review by LeonidVas — CHANGES_REQUESTED** [review]
Hi! Thank you for the patchset.
See several comments bellow.

File: t/220-mvcc.t (hunk 7 above)
Comment (better0fdead) [reply t/220-mvcc.t]: removed

File: t/220-mvcc.t (hunk 9 above)
Comment (better0fdead) [reply t/220-mvcc.t]: removed

File: t/220-mvcc.t (hunk 10 above)
Comment (better0fdead) [reply t/220-mvcc.t]: removed

File: t/220-mvcc.t (hunk 11 above)
Comment (better0fdead) [reply t/220-mvcc.t]: changed

File: t/220-mvcc.t (hunk 12 above)
Comment (better0fdead) [reply t/220-mvcc.t]: removed

File: t/220-mvcc.t (hunk 13 above)
Comment (better0fdead) [reply t/220-mvcc.t]: added

Comment (LeonidVas) [reply t/220-mvcc.t]: No)

File: t/220-mvcc.t (hunk 12 above)
Comment (LeonidVas) [reply t/220-mvcc.t]: No

File: t/220-mvcc.t (hunk 13 above)
Comment (better0fdead) [reply t/220-mvcc.t]: added

File: t/220-mvcc.t (hunk 12 above)
Comment (better0fdead) [reply t/220-mvcc.t]: Changed. Use channels to check results and to wait for fibres to finish work.

File: t/220-mvcc.t [hunk 14]
```diff
@@ -0,0 +1,72 @@
+#!/usr/bin/env tarantool
+local qc = require('queue.compat')
+local log   = require('log')
+if not qc.check_version({2, 6, 1}) then
+    log.info('Tests skipped, tarantool version < 2.6.1')
+    return
+end
+local yaml  = require('yaml')
```
Comment (LeonidVas) [inline t/220-mvcc.t:8]: As far as I can see, you are not using yaml below.

**Review by LeonidVas — CHANGES_REQUESTED** [review]

File: t/220-mvcc.t (hunk 14 above)
Comment (better0fdead) [reply t/220-mvcc.t]: deleted
